In [30]:
%pip -q install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [38]:
class Matrix:
    def __init__(self, matrix):
        self.matrix = matrix
    
    def T(self):
        result = []
        for j in range(len(self.matrix[0])):
            row = []
            for i in range(len(self.matrix)):
                row.append(self.matrix[i][j])
            result.append(row)
        
        return Matrix(result)

    def __add__(self, other):
        if len(self.matrix) != len(other.matrix) or len(self.matrix[0]) != len(other.matrix[0]):
            raise ValueError("Матрицы должны быть одинакового размера для сложения")
        
        result = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(self.matrix[0])):
                row.append(self.matrix[i][j] + other.matrix[i][j])
            result.append(row)
        
        return Matrix(result)
    
    def __sub__(self, other):
        if len(self.matrix) != len(other.matrix) or len(self.matrix[0]) != len(other.matrix[0]):
            raise ValueError("Матрицы должны быть одинакового размера для вычитания")
        
        result = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(self.matrix[0])):
                row.append(self.matrix[i][j] - other.matrix[i][j])
            result.append(row)
        
        return Matrix(result)
    
    def __mul__(self, other):
        if isinstance(other, (int, float)):
            result = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] * other)
                result.append(row)
            
            return Matrix(result)
        
        if len(self.matrix[0]) != len(other.matrix):
            raise ValueError("Количество столбцов в первой матрице должно быть равно количеству строк во второй матрице для умножения")
        
        result = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(other.matrix[0])):
                sum = 0
                for k in range(len(other.matrix)):
                    sum += self.matrix[i][k] * other.matrix[k][j]
                row.append(sum)
            result.append(row)
        
        return Matrix(result)
    
    def divide_scalar(self, scalar):
        result = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(self.matrix[0])):
                row.append(self.matrix[i][j] / scalar)
            result.append(row)
        
        return Matrix(result)
    
    def __truediv__(self, other):
        if isinstance(other, Matrix):
            if len(self.matrix) != len(other.matrix) or len(self.matrix[0]) != len(other.matrix[0]):
                raise ValueError("Матрицы должны быть одинакового размера для деления")

        result = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(self.matrix[0])):
                row.append(self.matrix[i][j] / other.matrix[i][j])
            result.append(row)

        return Matrix(result)
        raise ValueError("Деление матриц не определено")
    
    def __matmul__(self, other):
        if len(self.matrix[0]) != len(other.matrix):
            raise ValueError("Количество столбцов в первой матрице должно быть равно количеству строк во второй матрице для умножения скалярного произведения")
        
        result = 0
        for i in range(len(self.matrix)):
            for j in range(len(self.matrix[0])):
                result += self.matrix[i][j] * other.matrix[j][i]
        
        return result

In [39]:
matrix1 = [[1, 2, 3], 
           [4, 5, 6]]

matrix2 = [[7, 8, 9], 
           [10, 11, 12]]

my_matrix1 = Matrix(matrix1)
my_matrix2 = Matrix(matrix2)

result_matrix = my_matrix1 + my_matrix2
print("Сумма матриц (через Matrix):")
for row in result_matrix.matrix:
    print(row)

np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

np_result_matrix = np_matrix1 + np_matrix2
print("Сумма матриц (через NumPy):")
for row in np_result_matrix:
    print(row)

Сумма матриц (через Matrix):
[8, 10, 12]
[14, 16, 18]
Сумма матриц (через NumPy):
[ 8 10 12]
[14 16 18]


In [40]:
scalar = 2
result_matrix = my_matrix1.divide_scalar(scalar)

print("Деление матрицы на число (через Matrix):")
for row in result_matrix.matrix:
    print(row)

np_result_matrix = np_matrix1 / scalar

print("Деление матрицы на число (через NumPy):")
for row in np_result_matrix:
    print(row)

Деление матрицы на число (через Matrix):
[0.5, 1.0, 1.5]
[2.0, 2.5, 3.0]
Деление матрицы на число (через NumPy):
[0.5 1.  1.5]
[2.  2.5 3. ]


In [33]:
transposed_matrix = my_matrix1.T()
print("Транспонированная матрица через Matrix:")
for row in transposed_matrix.matrix:
    print(row)

np_transposed_matrix = np.transpose(np_matrix1)
print("Транспонированная матрица через NumPy:")
for row in np_transposed_matrix:
    print(row)

Транспонированная матрица через Matrix:
[1, 4]
[2, 5]
[3, 6]
Транспонированная матрица через NumPy:
[1 4]
[2 5]
[3 6]


In [34]:
result_matrix = my_matrix1 - my_matrix2
print("Вычитание матриц (через Matrix):")
for row in result_matrix.matrix:
    print(row)

np_result_matrix = np_matrix1 - np_matrix2
print("Вычитание матриц (через NumPy):")
for row in np_result_matrix:
    print(row)

Вычитание матриц (через Matrix):
[-6, -6, -6]
[-6, -6, -6]
Вычитание матриц (через NumPy):
[-6 -6 -6]
[-6 -6 -6]


In [36]:
matrix1 = [[1, 2, 3], 
           [4, 5, 6],
           [1, 2, 3]]

matrix2 = [[7, 8, 9],
           [1, 2, 3],
           [10, 11, 12]]

my_matrix1 = Matrix(matrix1)
my_matrix2 = Matrix(matrix2)

np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

result_matrix = my_matrix1 / my_matrix2
print("Деление матрицы на матрицу (через Matrix):")
for row in result_matrix.matrix:
    print(row)

np_result_matrix = np_matrix1 / np_matrix2
print("Деление матрицы на матрицу (через NumPy):")
for row in np_result_matrix:
    print(row)

Деление матрицы на матрицу (через Matrix):
[0.14285714285714285, 0.25, 0.3333333333333333]
[4.0, 2.5, 2.0]
[0.1, 0.18181818181818182, 0.25]
Деление матрицы на матрицу (через NumPy):
[0.14285714 0.25       0.33333333]
[4.  2.5 2. ]
[0.1        0.18181818 0.25      ]


In [42]:
matrix1 = [[1, 2, 3], 
           [4, 5, 6]]

matrix2 = [[7, 8, 9], 
           [10, 11, 12],
           [3, 5, 7]]

my_matrix1 = Matrix(matrix1)
my_matrix2 = Matrix(matrix2)

result_matrix = my_matrix1 * my_matrix2
print("Умножение матриц (через Matrix):")
for row in result_matrix.matrix:
    print(row)

number = 2
_result_matrix = my_matrix1 * 2
print(f"Умножение матрицы {matrix1} на число {number} (через Matrix):") #ВОТ ТУТ МОЖНО ПОСТАВИТЬ ЧИСЛО ВМЕСТО МАТРИЦЫ И БУДЕТ ТЕБЕ УМНОЖЕНИЕ НА ЧИСЛО
for row in _result_matrix.matrix:
    print(row)

np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

np_result_matrix = np_matrix1 @ np_matrix2
print("Умножение матриц (через NumPy):")
for row in np_result_matrix:
    print(row)

Умножение матриц (через Matrix):
[36, 45, 54]
[96, 117, 138]
Умножение матрицы [[1, 2, 3], [4, 5, 6]] на число 2 (через Matrix):
[2, 4, 6]
[8, 10, 12]
Умножение матриц (через NumPy):
[36 45 54]
[ 96 117 138]
